name: Metrics
on:
  schedule: [ { cron: "0 0 */7 * *" } ]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    name: Metrics generation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        name: Classic metrics
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
      - uses: lowlighter/metrics@v3.34
        name: LeetCode metrics
        with:
          filename: metrics.plugin.leetcode.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_user: NickSettler
          plugin_leetcode_sections: solved, skills, recent
      - uses: lowlighter/metrics@v3.34
        name: Calendar metrics
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
      - uses: lowlighter/metrics@v3.34
        name: Languages metrics
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
