name: Metrics
on:
  schedule: [ { cron: "0 0 */7 * *" } ]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    name: Metrics generation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3.34
        name: Classic metrics
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
      - uses: lowlighter/metrics@v3.34
        name: Calendar metrics
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes